import { app, BrowserWindow, session } from 'electron';
// import path from 'path';
import interceptToken from './backend/cookieIntercept'
import TokenStore from './backend/TokenStore';


// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
  app.quit();
}

let mainWindow:BrowserWindow

const createWindow = (): void => {
  // Create the browser window.
    mainWindow = new BrowserWindow({
    height: 600,
    width: 800,

    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: (process.env.ISDEV !== undefined) ? true : false
    }
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  const tokenStore = new TokenStore()

  session.defaultSession.webRequest.onBeforeRedirect({
    urls: [
      'https://account.xbox.com/*'
    ]
  }, interceptToken.bind(tokenStore))

  session.defaultSession.webRequest.onSendHeaders({
    urls: [
      'https://account.xbox.com/*'
    ]
  }, interceptToken.bind(tokenStore))

  tokenStore.addEventListener('onwebtoken', (tokens:any) => {
    mainWindow.webContents.executeJavaScript("setWebTokens('"+tokens.uhs+"', '"+tokens.userToken+"');");
  })

  tokenStore.addEventListener('onstreamingtoken', (token:any) => {
    mainWindow.webContents.executeJavaScript("setStreamingToken('"+token+"');");
  })

  createWindow()
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
