name: Build Workflow

on:
  push:
    branches:
      - main-v2
      - feature/*
    tags:
      - v*
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - main-v2
    paths:
      - 'packages/**'
      - 'yarn.lock'
      - '.github/workflows/*.yml'
  workflow_dispatch:
    inputs:
      reset_cache:
        description: 'Reset cache'
        required: false
        default: false
        type: boolean
      
env:
  node_version: 24
  reset_cache: ${{ inputs.reset_cache || false }}

jobs:
  ###
  # Build Desktop V2
  ###
  lint:
    name: "V2: Lint code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}
      
      - name: Set up node_modules cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Lint code
        run: yarn desktop lint

  tests:
    name: "V2: Run tests"
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}
      
      - name: Set up node_modules cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Install yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn desktop test


  cachedeps:
    name: "Global: Generate cached sources"
    runs-on: ubuntu-latest
    needs: ['tests']

    steps:
      # Install node tools
      - uses: actions/checkout@v7
        with:
          repository: 'flatpak/flatpak-builder-tools'

      - name: Install Python deps
        run: pip3 install aiohttp toml

      - name: Install flatpak-builder-tools
        run: pipx install ./node/

      # Generate sources
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive
          # clean: true

      - name: Prep artifacts dir
        run: mkdir ./deps-dist/

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build yarn cache
        run: flatpak-node-generator yarn yarn.lock -o ./deps-dist/yarn-sources.json

      - uses: actions/upload-artifact@master
        with:
          name: flatpak-sources
          path: ./deps-dist/

  flatpak:
    name: "V2: Flatpak Build"
    runs-on: ${{ matrix.os }}
    needs: [cachedeps]

    strategy:
      matrix:
        # os: ['ubuntu-latest', 'ubuntu-24.04-arm']
        os: ['ubuntu-latest']

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48 #bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions/download-artifact@master
        with:
          name: flatpak-sources
          path: packages/desktop/flatpak/

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Set up flatpak build cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            build/
            .flatpak-builder/
            flatpak-node/
          key: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-${{ hashFiles('flatpak/*') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: greenlight.flatpak
          manifest-path: packages/desktop/flatpak/io.github.unknownskl.greenlight.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Release flatpak
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/v2')
        with:
          files: greenlight.flatpak
          draft: true

  release:
    name: "V2: Build/release Electron app"
    runs-on: ${{ matrix.os }}
    needs: ['tests']

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Set up node_modules cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Install rimraf (if reset_cache enabled)
        if: env.reset_cache == 'true'
        run: npm install -g rimraf

      - name: Reset node_modules cache (if reset_cache enabled)
        if: env.reset_cache == 'true'
        run: rimraf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          package_root: packages/desktop
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v2') }}

      - name: Publish Linux AppImage
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-linux.AppImage
          path: |
            packages/desktop/dist/*.AppImage
        if: matrix.os == 'ubuntu-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Linux DEB
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-linux.deb
          path: |
            packages/desktop/dist/*.deb
        if: matrix.os == 'ubuntu-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Mac DMG
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-macos.dmg
          path: |
            packages/desktop/dist/*.dmg
        if: matrix.os == 'macos-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Windows EXE
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-win.zip
          path: |
            packages/desktop/dist/*.exe
        if: matrix.os == 'windows-latest' && contains(github.event.head_commit.message, '[build]')

  ###
  # Build Desktop V3
  ###

  test_v3:
    name: "V3: Run tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}
      
      - name: Set up node_modules cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build workspace dependencies
        run: yarn build:depsv3

      - name: Run tests
        run: yarn test:v3

  web_v3:
    name: "V3: Build Web App"
    runs-on: ubuntu-latest
    needs: test_v3

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Set up node_modules cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build workspace dependencies
        run: yarn build:depsv3

      - name: Build web app
        run: yarn build:depsv3 && yarn desktopv3 build:web

      - name: Publish web build
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-web
          path: |
            packages/desktop-v3/web-out/*

  flatpak_v3:
    name: "V3: Flatpak Build"
    runs-on: ubuntu-latest
    needs: [test_v3, cachedeps]

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - uses: actions/download-artifact@master
        with:
          name: flatpak-sources
          path: packages/desktop-v3/flatpak/

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Set up flatpak build cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            build/
            .flatpak-builder/
            flatpak-node/
          key: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-${{ hashFiles('flatpak/*') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: greenlight.flatpak
          manifest-path: packages/desktop-v3/flatpak/io.github.unknownskl.greenlight.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Publish Linux AppImage
        uses: actions/upload-artifact@v7
        with:
          name: greenlight.flatpak
          path: |
            greenlight.flatpak
        if: contains(github.event.head_commit.message, '[build]')

      - name: Release flatpak
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/v3')
        with:
          files: greenlight.flatpak
          draft: true

  release_v3:
    name: "V3: Build/release Electron app"
    runs-on: ${{ matrix.os }}
    needs: [test_v3]

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Set up node_modules cache
        uses: actions/cache@v5
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Install rimraf (if reset_cache enabled)
        if: env.reset_cache == 'true'
        run: npm install -g rimraf

      - name: Reset node_modules cache (if reset_cache enabled)
        if: env.reset_cache == 'true'
        run: rimraf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build workspace dependencies
        run: yarn build:depsv3

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          package_root: packages/desktop-v3
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v3') }}

      - name: Publish Linux AppImage
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-linux.AppImage
          path: |
            packages/desktop/dist/*.AppImage
        if: matrix.os == 'ubuntu-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Linux DEB
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-linux.deb
          path: |
            packages/desktop/dist/*.deb
        if: matrix.os == 'ubuntu-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Mac DMG
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-macos.dmg
          path: |
            packages/desktop/dist/*.dmg
        if: matrix.os == 'macos-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Windows EXE
        uses: actions/upload-artifact@v7
        with:
          name: greenlight-win.zip
          path: |
            packages/desktop/dist/*.exe
        if: matrix.os == 'windows-latest' && contains(github.event.head_commit.message, '[build]')

  ###
  # Build Docs
  ###

  build_docs:
    name: "Global: Build Docs"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.node_version }}

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn
  
      - name: Build docs
        run: yarn docs build

      - name: Upload static files as artifact
        id: deployment-pages
        uses: actions/upload-pages-artifact@v5 # or specific "vX.X.X" version tag for this action
        with:
          path: packages/docs/out/

  # Deployment job
  deploy:
    name: "Global: Deploy Docs"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_docs
    if: github.ref == 'refs/heads/main-v2'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment-pages
        uses: actions/deploy-pages@v5

      - name: Info
        run: echo "Deployed to ${{ steps.deployment-pages.outputs.page_url }}"

  ###
  # Dependabot Auto-Merge Check
  ###
  dependabot-merge:
    name: "Dependabot Auto-Merge Check"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]'
    needs: [build_docs, flatpak, release, flatpak_v3, release_v3]
    permissions:
      pull-requests: write
      contents: write
    steps:

      - name: Merge when build succeeds
        uses: actions/github-script@v9
        with:
          script: |
            console.log('Build passed, automerging Dependabot PR...');

            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: 'Build passed, automerging Dependabot PR...',
            });
            console.log('Dependabot PR approved successfully.');

            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'merge',
            });
            console.log('Dependabot PR merged successfully.');