name: Build/Desktop

on:
  push:
    branches:
      - main-v2
      - feature/*
    tags:
      - v*
    paths:
      - 'packages/desktop/**'
      - 'yarn.lock'
      - '.github/workflows/build_desktop.yml'
  pull_request:
    branches:
      - main-v2
    paths:
      - 'packages/desktop/**'
      - 'yarn.lock'
      - '.github/workflows/build_desktop.yml'
  workflow_dispatch:
    inputs:
      reset_cache:
        description: 'Reset cache'
        required: false
        default: false
        type: boolean
      
env:
  node_version: 22
  reset_cache: ${{ inputs.reset_cache || false }}

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ env.node_version }}
      
      - name: Set up node_modules cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Lint code
        run: yarn desktop lint

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: ['lint']
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ env.node_version }}
      
      - name: Set up node_modules cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Install yarn dependencies
        run: yarn

      - name: Run tests
        run: yarn desktop test


  cachedeps:
    name: Generate cached sources
    runs-on: ubuntu-latest
    needs: ['tests']

    steps:
      # Intsall node tools
      - uses: actions/checkout@v5
        with:
          repository: 'flatpak/flatpak-builder-tools'

      - name: Install Python deps
        run: pip3 install aiohttp toml

      - name: Install flatpak-builder-tools
        run: pipx install ./node/

      # Generate sources
      - name: Checkout Git repository
        uses: actions/checkout@v5
        with:
          submodules: recursive
          # clean: true

      - name: Prep artifacts dir
        run: mkdir ./deps-dist/

      - name: Reset node_modules cache (if enabled)
        if: env.reset_cache == 'true'
        run: rm -rf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build yarn cache
        run: flatpak-node-generator yarn yarn.lock -o ./deps-dist/yarn-sources.json

      - uses: actions/upload-artifact@master
        with:
          name: flatpak-sources
          path: ./deps-dist/

  flatpak:
    name: Flatpak Build
    runs-on: ubuntu-latest
    needs: [cachedeps]

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-45
      options: --privileged

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: actions/download-artifact@master
        with:
          name: flatpak-sources
          path: packages/desktop/flatpak/

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ env.node_version }}

      - name: Set up flatpak build cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            build/
            .flatpak-builder/
            flatpak-node/
          key: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-${{ hashFiles('flatpak/*') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-flatpak-builder-

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: greenlight.flatpak
          manifest-path: packages/desktop/flatpak/io.github.unknownskl.greenlight.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Release flatpak
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: greenlight.flatpak
          draft: true

  release:
    name: Build/release Electron app
    runs-on: ${{ matrix.os }}
    needs: ['tests']

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ env.node_version }}

      - name: Set up node_modules cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-yarn-

      - name: Install rimraf (if reset_cache enabled)
        if: env.reset_cache == 'true'
        run: npm install -g rimraf

      - name: Reset node_modules cache (if reset_cache enabled)
        if: env.reset_cache == 'true'
        run: rimraf node_modules/

      - name: Install yarn dependencies
        run: yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          package_root: packages/desktop
          github_token: ${{ secrets.github_token }}
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Publish Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: greenlight-linux.AppImage
          path: |
            dist/*.AppImage
        if: matrix.os == 'ubuntu-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Linux DEB
        uses: actions/upload-artifact@v4
        with:
          name: greenlight-linux.deb
          path: |
            dist/*.deb
        if: matrix.os == 'ubuntu-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Mac DMG
        uses: actions/upload-artifact@v4
        with:
          name: greenlight-macos.dmg
          path: |
            dist/*.dmg
        if: matrix.os == 'macos-latest' && contains(github.event.head_commit.message, '[build]')

      - name: Publish Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: greenlight-win.zip
          path: |
            dist/*.exe
        if: matrix.os == 'windows-latest' && contains(github.event.head_commit.message, '[build]')